# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: staskuznetsov
  # Overrides the image tag whose default is the chart appVersion.
  tag: "a204398-amd64"
  os: linux
  arch: amd64
secret:
  name: kbot
  tokenKey: token
  tokenName: TELE_TOKEN 

